language: python
python:
    - "3.5"
    - "3.6"

install:
    - pip install --upgrade -r requirements.txt
    - pip install --upgrade pytest pytest-cov pytest-django
    - pip install --upgrade coveralls

script:
    - ln -s tests/manage.py manage.py
    - py.test --cov --cov-config .coveragerc Artifactorial

after_success:
    coveralls
