language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"

install:
    - pip install -q -r requirements.txt --use-mirrors
    - pip install -q coveralls --use-mirrors

script:
    - coverage run --branch --source=Artifactorial tests/manage.py test Artifactorial

after_success:
    coveralls
